---
- name: Deploy application to WildFly domain
  hosts: all
  gather_facts: false
  vars_files:
    - ../group_vars/all/vars.yml
  tasks:
    - name: "Deploy application using wildfly_app_deploy role in domain mode"
      ansible.builtin.include_role:
        name: wildfly_app_deploy
      vars:
        wildfly_app_deploy_file: "{{ playbook_dir }}/../files/test-app.war"
        wildfly_app_deploy_name: "test-app.war"
        wildfly_app_deploy_mode: "domain"
        wildfly_app_deploy_server_groups:
          - main-server-group
        jboss_cli_controller_host: "localhost"
        jboss_cli_controller_port: "9990"



