---
- name: Validate deployment mode
  ansible.builtin.fail:
    msg: "wildfly_app_deploy_mode must be either 'standalone' or 'domain'"
  when: wildfly_app_deploy_mode not in ['standalone', 'domain']

- name: Copy application to remote server (if not already present)
  ansible.builtin.copy:
    src: "{{ wildfly_app_deployment_file }}"
    dest: "/tmp/{{ wildfly_app_deploy_name }}"
    mode: '0644'

- name: Deploy to Standalone
  ansible.builtin.include_tasks: standalone.yml
  when: wildfly_app_deploy_mode == 'standalone'

- name: Deploy to Managed Domain
  ansible.builtin.include_tasks: domain.yml
  when: wildfly_app_deploy_mode == 'domain'
